version: '3.8'
services:
  api:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: mariadb:10.6.4
    restart: always
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      - MYSQL_USER=homage
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=homage
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306